export interface Element {
	elemSymbol: string;
	elemName: string;
	period: number;
	group: number;
	atomicNumber: number;
	valenceElectrons: number;
	block: string;
	electronegativity: number;
}

// elemSymbol, elemName, period, group, atomicNumber, valenceElectrons, block, electronegativity
export const elements: Element[] = [
	{
		elemSymbol: "H",
		elemName: "Hydrogen",
		period: 1,
		group: 1,
		atomicNumber: 1,
		valenceElectrons: 1,
		block: "s",
		electronegativity: 2.2,
	},
	{
		elemSymbol: "He",
		elemName: "Helium",
		period: 1,
		group: 18,
		atomicNumber: 2,
		valenceElectrons: 2,
		block: "s",
		electronegativity: 0,
	},
	{
		elemSymbol: "Li",
		elemName: "Lithium",
		period: 2,
		group: 1,
		atomicNumber: 3,
		valenceElectrons: 1,
		block: "s",
		electronegativity: 0.98,
	},
	{
		elemSymbol: "Be",
		elemName: "Beryllium",
		period: 2,
		group: 2,
		atomicNumber: 4,
		valenceElectrons: 2,
		block: "s",
		electronegativity: 1.57,
	},
	{
		elemSymbol: "B",
		elemName: "Boron",
		period: 2,
		group: 13,
		atomicNumber: 5,
		valenceElectrons: 3,
		block: "p",
		electronegativity: 2.04,
	},
	{
		elemSymbol: "C",
		elemName: "Carbon",
		period: 2,
		group: 14,
		atomicNumber: 6,
		valenceElectrons: 4,
		block: "p",
		electronegativity: 2.55,
	},
	{
		elemSymbol: "N",
		elemName: "Nitrogen",
		period: 2,
		group: 15,
		atomicNumber: 7,
		valenceElectrons: 5,
		block: "p",
		electronegativity: 3.04,
	},
	{
		elemSymbol: "O",
		elemName: "Oxygen",
		period: 2,
		group: 16,
		atomicNumber: 8,
		valenceElectrons: 6,
		block: "p",
		electronegativity: 3.44,
	},
	{
		elemSymbol: "F",
		elemName: "Fluorine",
		period: 2,
		group: 17,
		atomicNumber: 9,
		valenceElectrons: 7,
		block: "p",
		electronegativity: 3.98,
	},
	{
		elemSymbol: "Ne",
		elemName: "Neon",
		period: 2,
		group: 18,
		atomicNumber: 10,
		valenceElectrons: 8,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "Na",
		elemName: "Sodium",
		period: 3,
		group: 1,
		atomicNumber: 11,
		valenceElectrons: 1,
		block: "s",
		electronegativity: 0.93,
	},
	{
		elemSymbol: "Mg",
		elemName: "Magnesium",
		period: 3,
		group: 2,
		atomicNumber: 12,
		valenceElectrons: 2,
		block: "s",
		electronegativity: 1.31,
	},
	{
		elemSymbol: "Al",
		elemName: "Aluminium",
		period: 3,
		group: 13,
		atomicNumber: 13,
		valenceElectrons: 3,
		block: "p",
		electronegativity: 1.61,
	},
	{
		elemSymbol: "Si",
		elemName: "Silicon",
		period: 3,
		group: 14,
		atomicNumber: 14,
		valenceElectrons: 4,
		block: "p",
		electronegativity: 1.9,
	},
	{
		elemSymbol: "P",
		elemName: "Phosphorus",
		period: 3,
		group: 15,
		atomicNumber: 15,
		valenceElectrons: 5,
		block: "p",
		electronegativity: 2.19,
	},
	{
		elemSymbol: "S",
		elemName: "Sulfur",
		period: 3,
		group: 16,
		atomicNumber: 16,
		valenceElectrons: 6,
		block: "p",
		electronegativity: 2.58,
	},
	{
		elemSymbol: "Cl",
		elemName: "Chlorine",
		period: 3,
		group: 17,
		atomicNumber: 17,
		valenceElectrons: 7,
		block: "p",
		electronegativity: 3.16,
	},
	{
		elemSymbol: "Ar",
		elemName: "Argon",
		period: 3,
		group: 18,
		atomicNumber: 18,
		valenceElectrons: 8,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "K",
		elemName: "Potassium",
		period: 4,
		group: 1,
		atomicNumber: 19,
		valenceElectrons: 1,
		block: "s",
		electronegativity: 0.82,
	},
	{
		elemSymbol: "Ca",
		elemName: "Calcium",
		period: 4,
		group: 2,
		atomicNumber: 20,
		valenceElectrons: 2,
		block: "s",
		electronegativity: 1,
	},
	{
		elemSymbol: "Sc",
		elemName: "Scandium",
		period: 4,
		group: 3,
		atomicNumber: 21,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.36,
	},
	{
		elemSymbol: "Ti",
		elemName: "Titanium",
		period: 4,
		group: 4,
		atomicNumber: 22,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.54,
	},
	{
		elemSymbol: "V",
		elemName: "Vanadium",
		period: 4,
		group: 5,
		atomicNumber: 23,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.63,
	},
	{
		elemSymbol: "Cr",
		elemName: "Chromium",
		period: 4,
		group: 6,
		atomicNumber: 24,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 1.66,
	},
	{
		elemSymbol: "Mn",
		elemName: "Manganese",
		period: 4,
		group: 7,
		atomicNumber: 25,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.55,
	},
	{
		elemSymbol: "Fe",
		elemName: "Iron",
		period: 4,
		group: 8,
		atomicNumber: 26,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.83,
	},
	{
		elemSymbol: "Co",
		elemName: "Cobalt",
		period: 4,
		group: 9,
		atomicNumber: 27,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.88,
	},
	{
		elemSymbol: "Ni",
		elemName: "Nickel",
		period: 4,
		group: 10,
		atomicNumber: 28,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.91,
	},
	{
		elemSymbol: "Cu",
		elemName: "Copper",
		period: 4,
		group: 11,
		atomicNumber: 29,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 1.9,
	},
	{
		elemSymbol: "Zn",
		elemName: "Zinc",
		period: 4,
		group: 12,
		atomicNumber: 30,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.65,
	},
	{
		elemSymbol: "Ga",
		elemName: "Gallium",
		period: 4,
		group: 13,
		atomicNumber: 31,
		valenceElectrons: 3,
		block: "p",
		electronegativity: 1.81,
	},
	{
		elemSymbol: "Ge",
		elemName: "Germanium",
		period: 4,
		group: 14,
		atomicNumber: 32,
		valenceElectrons: 4,
		block: "p",
		electronegativity: 2.01,
	},
	{
		elemSymbol: "As",
		elemName: "Arsenic",
		period: 4,
		group: 15,
		atomicNumber: 33,
		valenceElectrons: 5,
		block: "p",
		electronegativity: 2.18,
	},
	{
		elemSymbol: "Se",
		elemName: "Selenium",
		period: 4,
		group: 16,
		atomicNumber: 34,
		valenceElectrons: 6,
		block: "p",
		electronegativity: 2.55,
	},
	{
		elemSymbol: "Br",
		elemName: "Bromine",
		period: 4,
		group: 17,
		atomicNumber: 35,
		valenceElectrons: 7,
		block: "p",
		electronegativity: 2.96,
	},
	{
		elemSymbol: "Kr",
		elemName: "Krypton",
		period: 4,
		group: 18,
		atomicNumber: 36,
		valenceElectrons: 8,
		block: "p",
		electronegativity: 3,
	},
	{
		elemSymbol: "Rb",
		elemName: "Rubidium",
		period: 5,
		group: 1,
		atomicNumber: 37,
		valenceElectrons: 1,
		block: "s",
		electronegativity: 0.82,
	},
	{
		elemSymbol: "Sr",
		elemName: "Strontium",
		period: 5,
		group: 2,
		atomicNumber: 38,
		valenceElectrons: 2,
		block: "s",
		electronegativity: 0.95,
	},
	{
		elemSymbol: "Y",
		elemName: "Yttrium",
		period: 5,
		group: 3,
		atomicNumber: 39,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.22,
	},
	{
		elemSymbol: "Zr",
		elemName: "Zirconium",
		period: 5,
		group: 4,
		atomicNumber: 40,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.33,
	},
	{
		elemSymbol: "Nb",
		elemName: "Niobium",
		period: 5,
		group: 5,
		atomicNumber: 41,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 1.6,
	},
	{
		elemSymbol: "Mo",
		elemName: "Molybdenum",
		period: 5,
		group: 6,
		atomicNumber: 42,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 2.16,
	},
	{
		elemSymbol: "Tc",
		elemName: "Technetium",
		period: 5,
		group: 7,
		atomicNumber: 43,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 1.9,
	},
	{
		elemSymbol: "Ru",
		elemName: "Ruthenium",
		period: 5,
		group: 8,
		atomicNumber: 44,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 2.2,
	},
	{
		elemSymbol: "Rh",
		elemName: "Rhodium",
		period: 5,
		group: 9,
		atomicNumber: 45,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 2.28,
	},
	{
		elemSymbol: "Pd",
		elemName: "Palladium",
		period: 5,
		group: 10,
		atomicNumber: 46,
		valenceElectrons: 0,
		block: "d",
		electronegativity: 2.2,
	},
	{
		elemSymbol: "Ag",
		elemName: "Silver",
		period: 5,
		group: 11,
		atomicNumber: 47,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 1.93,
	},
	{
		elemSymbol: "Cd",
		elemName: "Cadmium",
		period: 5,
		group: 12,
		atomicNumber: 48,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.69,
	},
	{
		elemSymbol: "In",
		elemName: "Indium",
		period: 5,
		group: 13,
		atomicNumber: 49,
		valenceElectrons: 3,
		block: "p",
		electronegativity: 1.78,
	},
	{
		elemSymbol: "Sn",
		elemName: "Tin",
		period: 5,
		group: 14,
		atomicNumber: 50,
		valenceElectrons: 4,
		block: "p",
		electronegativity: 1.96,
	},
	{
		elemSymbol: "Sb",
		elemName: "Antimony",
		period: 5,
		group: 15,
		atomicNumber: 51,
		valenceElectrons: 5,
		block: "p",
		electronegativity: 2.05,
	},
	{
		elemSymbol: "Te",
		elemName: "Tellurium",
		period: 5,
		group: 16,
		atomicNumber: 52,
		valenceElectrons: 6,
		block: "p",
		electronegativity: 2.1,
	},
	{
		elemSymbol: "I",
		elemName: "Iodine",
		period: 5,
		group: 17,
		atomicNumber: 53,
		valenceElectrons: 7,
		block: "p",
		electronegativity: 2.66,
	},
	{
		elemSymbol: "Xe",
		elemName: "Xenon",
		period: 5,
		group: 18,
		atomicNumber: 54,
		valenceElectrons: 8,
		block: "p",
		electronegativity: 2.6,
	},
	{
		elemSymbol: "Cs",
		elemName: "Caesium",
		period: 6,
		group: 1,
		atomicNumber: 55,
		valenceElectrons: 1,
		block: "s",
		electronegativity: 0.79,
	},
	{
		elemSymbol: "Ba",
		elemName: "Barium",
		period: 6,
		group: 2,
		atomicNumber: 56,
		valenceElectrons: 2,
		block: "s",
		electronegativity: 0.89,
	},
	{
		elemSymbol: "La",
		elemName: "Lanthanum",
		period: 6,
		group: 0,
		atomicNumber: 57,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.1,
	},
	{
		elemSymbol: "Ce",
		elemName: "Cerium",
		period: 6,
		group: 0,
		atomicNumber: 58,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.12,
	},
	{
		elemSymbol: "Pr",
		elemName: "Praseodymium",
		period: 6,
		group: 0,
		atomicNumber: 59,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.13,
	},
	{
		elemSymbol: "Nd",
		elemName: "Neodymium",
		period: 6,
		group: 0,
		atomicNumber: 60,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.14,
	},
	{
		elemSymbol: "Pm",
		elemName: "Promethium",
		period: 6,
		group: 0,
		atomicNumber: 61,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.13,
	},
	{
		elemSymbol: "Sm",
		elemName: "Samarium",
		period: 6,
		group: 0,
		atomicNumber: 62,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.17,
	},
	{
		elemSymbol: "Eu",
		elemName: "Europium",
		period: 6,
		group: 0,
		atomicNumber: 63,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.2,
	},
	{
		elemSymbol: "Gd",
		elemName: "Gadolinium",
		period: 6,
		group: 0,
		atomicNumber: 64,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.2,
	},
	{
		elemSymbol: "Tb",
		elemName: "Terbium",
		period: 6,
		group: 0,
		atomicNumber: 65,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.22,
	},
	{
		elemSymbol: "Dy",
		elemName: "Dysprosium",
		period: 6,
		group: 0,
		atomicNumber: 66,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.23,
	},
	{
		elemSymbol: "Ho",
		elemName: "Holmium",
		period: 6,
		group: 0,
		atomicNumber: 67,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.24,
	},
	{
		elemSymbol: "Er",
		elemName: "Erbium",
		period: 6,
		group: 0,
		atomicNumber: 68,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.24,
	},
	{
		elemSymbol: "Tm",
		elemName: "Thulium",
		period: 6,
		group: 0,
		atomicNumber: 69,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.25,
	},
	{
		elemSymbol: "Yb",
		elemName: "Ytterbium",
		period: 6,
		group: 0,
		atomicNumber: 70,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.1,
	},
	{
		elemSymbol: "Lu",
		elemName: "Lutetium",
		period: 6,
		group: 3,
		atomicNumber: 71,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.27,
	},
	{
		elemSymbol: "Hf",
		elemName: "Hafnium",
		period: 6,
		group: 4,
		atomicNumber: 72,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Ta",
		elemName: "Tantalum",
		period: 6,
		group: 5,
		atomicNumber: 73,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.5,
	},
	{
		elemSymbol: "W",
		elemName: "Tungsten",
		period: 6,
		group: 6,
		atomicNumber: 74,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 2.36,
	},
	{
		elemSymbol: "Re",
		elemName: "Rhenium",
		period: 6,
		group: 7,
		atomicNumber: 75,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 1.9,
	},
	{
		elemSymbol: "Os",
		elemName: "Osmium",
		period: 6,
		group: 8,
		atomicNumber: 76,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 2.2,
	},
	{
		elemSymbol: "Ir",
		elemName: "Iridium",
		period: 6,
		group: 9,
		atomicNumber: 77,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 2.2,
	},
	{
		elemSymbol: "Pt",
		elemName: "Platinum",
		period: 6,
		group: 10,
		atomicNumber: 78,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 2.28,
	},
	{
		elemSymbol: "Au",
		elemName: "Gold",
		period: 6,
		group: 11,
		atomicNumber: 79,
		valenceElectrons: 1,
		block: "d",
		electronegativity: 2.54,
	},
	{
		elemSymbol: "Hg",
		elemName: "Mercury",
		period: 6,
		group: 12,
		atomicNumber: 80,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 2,
	},
	{
		elemSymbol: "Tl",
		elemName: "Thallium",
		period: 6,
		group: 13,
		atomicNumber: 81,
		valenceElectrons: 3,
		block: "p",
		electronegativity: 1.62,
	},
	{
		elemSymbol: "Pb",
		elemName: "Lead",
		period: 6,
		group: 14,
		atomicNumber: 82,
		valenceElectrons: 4,
		block: "p",
		electronegativity: 2.33,
	},
	{
		elemSymbol: "Bi",
		elemName: "Bismuth",
		period: 6,
		group: 15,
		atomicNumber: 83,
		valenceElectrons: 5,
		block: "p",
		electronegativity: 2.02,
	},
	{
		elemSymbol: "Po",
		elemName: "Polonium",
		period: 6,
		group: 16,
		atomicNumber: 84,
		valenceElectrons: 6,
		block: "p",
		electronegativity: 2,
	},
	{
		elemSymbol: "At",
		elemName: "Astatine",
		period: 6,
		group: 17,
		atomicNumber: 85,
		valenceElectrons: 7,
		block: "p",
		electronegativity: 2.2,
	},
	{
		elemSymbol: "Rn",
		elemName: "Radon",
		period: 6,
		group: 18,
		atomicNumber: 86,
		valenceElectrons: 8,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "Fr",
		elemName: "Francium",
		period: 7,
		group: 1,
		atomicNumber: 87,
		valenceElectrons: 1,
		block: "s",
		electronegativity: 0.7,
	},
	{
		elemSymbol: "Ra",
		elemName: "Radium",
		period: 7,
		group: 2,
		atomicNumber: 88,
		valenceElectrons: 2,
		block: "s",
		electronegativity: 0.89,
	},
	{
		elemSymbol: "Ac",
		elemName: "Actinium",
		period: 7,
		group: 0,
		atomicNumber: 89,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.1,
	},
	{
		elemSymbol: "Th",
		elemName: "Thorium",
		period: 7,
		group: 0,
		atomicNumber: 90,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Pa",
		elemName: "Protactinium",
		period: 7,
		group: 0,
		atomicNumber: 91,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.5,
	},
	{
		elemSymbol: "U",
		elemName: "Uranium",
		period: 7,
		group: 0,
		atomicNumber: 92,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.38,
	},
	{
		elemSymbol: "Np",
		elemName: "Neptunium",
		period: 7,
		group: 0,
		atomicNumber: 93,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.36,
	},
	{
		elemSymbol: "Pu",
		elemName: "Plutonium",
		period: 7,
		group: 0,
		atomicNumber: 94,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.28,
	},
	{
		elemSymbol: "Am",
		elemName: "Americium",
		period: 7,
		group: 0,
		atomicNumber: 95,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Cm",
		elemName: "Curium",
		period: 7,
		group: 0,
		atomicNumber: 96,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Bk",
		elemName: "Berkelium",
		period: 7,
		group: 0,
		atomicNumber: 97,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Cf",
		elemName: "Californium",
		period: 7,
		group: 0,
		atomicNumber: 98,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Es",
		elemName: "Einsteinium",
		period: 7,
		group: 0,
		atomicNumber: 99,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Fm",
		elemName: "Fermium",
		period: 7,
		group: 0,
		atomicNumber: 100,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Md",
		elemName: "Mendelevium",
		period: 7,
		group: 0,
		atomicNumber: 101,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "No",
		elemName: "Nobelium",
		period: 7,
		group: 0,
		atomicNumber: 102,
		valenceElectrons: 2,
		block: "f",
		electronegativity: 1.3,
	},
	{
		elemSymbol: "Lr",
		elemName: "Lawrencium",
		period: 7,
		group: 3,
		atomicNumber: 103,
		valenceElectrons: 3,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Rf",
		elemName: "Rutherfordium",
		period: 7,
		group: 4,
		atomicNumber: 104,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Db",
		elemName: "Dubnium",
		period: 7,
		group: 5,
		atomicNumber: 105,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Sg",
		elemName: "Seaborgium",
		period: 7,
		group: 6,
		atomicNumber: 106,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Bh",
		elemName: "Bohrium",
		period: 7,
		group: 7,
		atomicNumber: 107,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Hs",
		elemName: "Hassium",
		period: 7,
		group: 8,
		atomicNumber: 108,
		valenceElectrons: 2,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Mt",
		elemName: "Meitnerium",
		period: 7,
		group: 9,
		atomicNumber: 109,
		valenceElectrons: 0,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Ds",
		elemName: "Darmstadtium",
		period: 7,
		group: 10,
		atomicNumber: 110,
		valenceElectrons: 0,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Rg",
		elemName: "Roentgenium",
		period: 7,
		group: 11,
		atomicNumber: 111,
		valenceElectrons: 0,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Cn",
		elemName: "Copernicium",
		period: 7,
		group: 12,
		atomicNumber: 112,
		valenceElectrons: 0,
		block: "d",
		electronegativity: 0,
	},
	{
		elemSymbol: "Nh",
		elemName: "Nihonium",
		period: 7,
		group: 13,
		atomicNumber: 113,
		valenceElectrons: 0,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "Fl",
		elemName: "Flerovium",
		period: 7,
		group: 14,
		atomicNumber: 114,
		valenceElectrons: 0,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "Mc",
		elemName: "Moscovium",
		period: 7,
		group: 15,
		atomicNumber: 115,
		valenceElectrons: 0,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "Lv",
		elemName: "Livermorium",
		period: 7,
		group: 16,
		atomicNumber: 116,
		valenceElectrons: 0,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "Ts",
		elemName: "Tennessine",
		period: 7,
		group: 17,
		atomicNumber: 117,
		valenceElectrons: 0,
		block: "p",
		electronegativity: 0,
	},
	{
		elemSymbol: "Og",
		elemName: "Oganesson",
		period: 7,
		group: 18,
		atomicNumber: 118,
		valenceElectrons: 0,
		block: "p",
		electronegativity: 0,
	},
];
